version: '3.8'

services:
  notification-service:
    build: .
    container_name: qarum-notification
    restart: always
    env_file:
      - .env
    ports:
      - "${PORT:-8000}:8000"
    environment:
      - PORT=8000
